#
# The configuration file for verify_age
# 

# You may need to specify the file path to the doc root of your website, if
# so you may enter it here
#document_root: '/some/file/path'

# The path from document root to the root of verify_age/
base_path: '/verify_age/'

# Enter the url (relative if within your site, or absolute if to another 
# external website) to display when they have have not met the age requirements.
url_403: /page-underage.php
#url_403: http://www.youtube.com/watch?v=gppbrYIcR80

# Snippets will be parsed for the following variables:
#   {{ deny.href }}
#   {{ verify.href }}
# These paths should begin with / and be relative to the document root.
#   
# The contents of this file will show when a user is unverified.  
# This is the default file and should not be modified
snippet_enter: /yes-no.html.twig
# If you want to modify the file use this
#snippet_enter: /verify_age/user/over-21.html.twig

# The contents of this file will show when a user is verified. You may comment
# this out to not have anything show in for this case
# Again do not edit this file, instead use the next line
snippet_exit:  /verify_age/exit.html.twig
#snippet_exit:  /verify_age/user/exit.html.twig

# This snippet will be presented when a user hits the validate.php page without
# proper input variables
snippet_403: /verify_age/403.html.twig

# Enter the minimum age necessary to enter
min_age: 5

# width/height in pixels of the popup container, e.g., 400
width: 500
height: 300

# Background color of the overlay
overlay: '#000'

# Include jquery from CDN; you should DISABLE this if jquery is already present in your project.
jquery_cdn: true
